/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bartender.view;
import br.com.bartender.model.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardo_niederauer
 */
public class NovoProdutoUI extends javax.swing.JInternalFrame {
private Produto produtoAlterar;

    public NovoProdutoUI(Produto produto) {
       initComponents();

       if(produto != null){

           produtoAlterar = produto;
           jtfProdutoNome.setText(produto.getNomeProduto());
           jtfProdutoTipo.setText(produto.getTipoProduto());
           jtfProdutoValor.setText(produto.getValorProduto().toString());

       }
    }

    NovoProdutoUI() {
       throw new UnsupportedOperationException("Not yet implemented");
    /**
     * Creates new form NovoProdutoUI
     */
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfProdutoNome = new javax.swing.JTextField();
        jtfProdutoTipo = new javax.swing.JTextField();
        jtfProdutoValor = new javax.swing.JTextField();

        jLabel1.setText("Nome");

        jLabel2.setText("Tipo");

        jLabel3.setText("Valor");

        jtfProdutoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProdutoNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfProdutoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfProdutoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfProdutoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfProdutoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfProdutoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProdutoNomeActionPerformed
        // TODO add your handling code here:try{
           try{
           if(produtoAlterar != null){

               produtoAlterar.setNomeProduto(jtfProdutoNome.getText());

               produtoAlterar.setTipoProduto(jtfProdutoTipo.getText());

               produtoAlterar.setValorProduto(Double.parseDouble(jtfProdutoValor.getText()));

               /* ProdutoController.obterInstancia().alterar(produtoAlteracao);*/

           }else {

               Produto produto = new Produto();

             

               produto.setNomeProduto(jtfProdutoNome.getText());

               produto.setTipoProduto(jtfProdutoTipo.getText());

               produto.setValorProduto(Double.parseDouble(jtfProdutoValor.getText()));

               /* ProdutoController.obterInstancia().alterar(produtoAlteracao);*/

               JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso.");

           }

           this.dispose();
            }catch(Exception e){

           JOptionPane.showMessageDialog(null, e.getMessage());
       }     
          
    }//GEN-LAST:event_jtfProdutoNomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfProdutoNome;
    private javax.swing.JTextField jtfProdutoTipo;
    private javax.swing.JTextField jtfProdutoValor;
    // End of variables declaration//GEN-END:variables
}
