/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bartender.view;

import br.com.bartender.controller.ConsumoController;
import br.com.bartender.model.Comanda;
import br.com.bartender.model.Consumo;
import br.com.bartender.model.Produto;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduardo
 */
public class TelaPrincipalUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrincipalUI
     */
    private static TelaPrincipalUI instanciaRep;
    private ArrayList<Consumo> listaConsumoTemp;
    
    public static TelaPrincipalUI obterInstancia(){
        if ( instanciaRep == null ){
            instanciaRep = new TelaPrincipalUI();
        }
        return instanciaRep;
    }

    public JDesktopPane getPainelPrincipal(){
        return obterInstancia().getPainelPrincipal();    
    }
    public TelaPrincipalUI() {
        initComponents();
    }
    
    public void atualizarTabelaConsumo(){
        DefaultTableModel tabelaConsumoTemp = new DefaultTableModel();
        tabelaConsumoTemp.setColumnIdentifiers(new String[] {"Codigo de barras","Descrição","Preço"});
        
        for ( int i=0; i < this.listaConsumoTemp.size(); i++){
            tabelaConsumoTemp.addRow(new Object[] { this.listaConsumoTemp.get(i).getProdutoInserido().getNomeProduto(), 
                this.listaConsumoTemp.get(i).getProdutoInserido().getValorProduto(), this.listaConsumoTemp.get(i).getQuantidadeProduto(), 
            this.listaConsumoTemp.get(i).getValorTotal() });
        }
        jtListaConsumoTemp.setModel(tabelaConsumoTemp);        
    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPainelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfBotaoEvento = new javax.swing.JButton();
        jtfBotaoComanda = new javax.swing.JButton();
        jtfBotaoProduto = new javax.swing.JButton();
        jtfBotaoRelatorio = new javax.swing.JButton();
        jtfBotaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfIdComanda = new javax.swing.JTextField();
        jbBuscarComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaConsumoTemp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jbAdicionarConsumo = new javax.swing.JButton();
        jtfIdProduto = new javax.swing.JTextField();
        jbCadastrarConsumo = new javax.swing.JButton();
        jbLimparConsumo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfQuantidadeConsumo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jlNomeEvento = new javax.swing.JLabel();
        jlDataEvento = new javax.swing.JLabel();
        jlHorarioEvento = new javax.swing.JLabel();

        jdpPainelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jdpPainelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jdpPainelPrincipal.setForeground(new java.awt.Color(255, 0, 153));
        jdpPainelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bartender/view/BarTenderLogo-Preto.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jtfBotaoEvento.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoEvento.setText("Evento");
        jtfBotaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoEventoActionPerformed(evt);
            }
        });

        jtfBotaoComanda.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoComanda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoComanda.setText("Comanda");
        jtfBotaoComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoComandaActionPerformed(evt);
            }
        });

        jtfBotaoProduto.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoProduto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoProduto.setText("Produto");
        jtfBotaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoProdutoActionPerformed(evt);
            }
        });

        jtfBotaoRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoRelatorio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoRelatorio.setText("Relatório");
        jtfBotaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoRelatorioActionPerformed(evt);
            }
        });

        jtfBotaoSair.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoSair.setText("Sair");
        jtfBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 228, 228));
        jLabel1.setText("Bartender v1.0 - All Rights Reserved");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Comanda:");

        jtfIdComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdComandaActionPerformed(evt);
            }
        });

        jbBuscarComanda.setText("Buscar");
        jbBuscarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarComandaActionPerformed(evt);
            }
        });

        jtListaConsumoTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ));
        jtListaConsumoTemp.setGridColor(new java.awt.Color(0, 0, 0));
        jtListaConsumoTemp.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jtListaConsumoTemp.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jtListaConsumoTempComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaConsumoTemp);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Produto:");

        jbAdicionarConsumo.setText("Adicionar");
        jbAdicionarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarConsumoActionPerformed(evt);
            }
        });

        jbCadastrarConsumo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbCadastrarConsumo.setText("Inserir");
        jbCadastrarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarConsumoActionPerformed(evt);
            }
        });

        jbLimparConsumo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbLimparConsumo.setText("Limpar");
        jbLimparConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparConsumoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Consumo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfIdComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfQuantidadeConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdicionarConsumo)))
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jbCadastrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jbLimparConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIdComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarComanda)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarConsumo)
                    .addComponent(jtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQuantidadeConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimparConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(1, 1, 1));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 254, 254), 2, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Evento");

        jlNomeEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlNomeEvento.setForeground(new java.awt.Color(255, 255, 255));
        jlNomeEvento.setText("Evento");

        jlDataEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlDataEvento.setForeground(new java.awt.Color(255, 255, 255));
        jlDataEvento.setText("Evento");

        jlHorarioEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlHorarioEvento.setForeground(new java.awt.Color(255, 255, 255));
        jlHorarioEvento.setText("Evento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlNomeEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jlDataEvento))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addGap(30, 30, 30)
                .addComponent(jlHorarioEvento)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDataEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlHorarioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdpPainelPrincipalLayout = new javax.swing.GroupLayout(jdpPainelPrincipal);
        jdpPainelPrincipal.setLayout(jdpPainelPrincipalLayout);
        jdpPainelPrincipalLayout.setHorizontalGroup(
            jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(391, 391, 391)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBotaoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBotaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBotaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jtfBotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jtfBotaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jdpPainelPrincipalLayout.setVerticalGroup(
            jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jtfBotaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jtfBotaoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jtfBotaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jtfBotaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jtfBotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Se fosse na quarta fase, este trabalho não passava.");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jtfBotaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoEventoActionPerformed
        // TODO add your handling code here:
        ManutencaoEventoUI manutencaoEvento = new ManutencaoEventoUI();
        manutencaoEvento.setVisible(true);

    }//GEN-LAST:event_jtfBotaoEventoActionPerformed

    private void jtfBotaoComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoComandaActionPerformed
        // TODO add your handling code here:
        ManutencaoComandaUI manutencaoComanda = new ManutencaoComandaUI();
        manutencaoComanda.setVisible(true);
    }//GEN-LAST:event_jtfBotaoComandaActionPerformed

    private void jtfBotaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoProdutoActionPerformed
        // TODO add your handling code here:
        ManutencaoProdutoUI manutencaoProduto = new ManutencaoProdutoUI();
        manutencaoProduto.setVisible(true);
    }//GEN-LAST:event_jtfBotaoProdutoActionPerformed

    private void jtfBotaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoRelatorioActionPerformed
        // TODO add your handling code here:
        /*RelatorioUI relatorioUI = new RelatorioUI();
        relatorioUI.setVisible(true);*/
    }//GEN-LAST:event_jtfBotaoRelatorioActionPerformed

    private void jtfBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jtfBotaoSairActionPerformed

    private void jtfIdComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdComandaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtfIdComandaActionPerformed

    private void jbBuscarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarComandaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbBuscarComandaActionPerformed

    private void jtListaConsumoTempComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jtListaConsumoTempComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtListaConsumoTempComponentAdded

    private void jbAdicionarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarConsumoActionPerformed
        // TODO add your handling code here:

        Consumo consumo = new Consumo();
        Comanda comandaRelacionada = new Comanda();
        Produto produtoInserido = new Produto();
        double valorTotal = 0;
        
        comandaRelacionada.setIdComanda(Integer.parseInt(jtfIdComanda.getText()));
        produtoInserido.setIdProduto(Integer.parseInt(jtfIdProduto.getText()));
        
        /*
         * Trecho pra testar sem o banco
         */
        produtoInserido.setNomeProduto("Coca-Cola");
        produtoInserido.setValorProduto(5D);
        /*
         * Fim do trecho
         */
        
        consumo.setComandaRelacionada(comandaRelacionada);
        consumo.setProdutoInserido(produtoInserido);
        consumo.setQuantidadeProduto(Integer.parseInt(jtfQuantidadeConsumo.getText()));
        
        this.listaConsumoTemp.add(consumo);
        atualizarTabelaConsumo();
        
        
        
        
        
        
        /*
        jtListaConsumoTemp.setValueAt(consumo.getProdutoInserido().getNomeProduto(), 0, 0);
        jtListaConsumoTemp.setValueAt(consumo.getProdutoInserido().getValorProduto(), 0, 1);
        jtListaConsumoTemp.setValueAt(consumo.getQuantidadeProduto(),0, 2);
        
        valorTotal = consumo.getQuantidadeProduto() * consumo.getProdutoInserido().getValorProduto();
        
        jtListaConsumoTemp.setValueAt(valorTotal, 0, 3);
        */


    }//GEN-LAST:event_jbAdicionarConsumoActionPerformed

    private void jbLimparConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparConsumoActionPerformed
        // TODO add your handling code here:
        
        this.listaConsumoTemp.clear();
    }//GEN-LAST:event_jbLimparConsumoActionPerformed

    private void jbCadastrarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarConsumoActionPerformed
        // TODO add your handling code here:
        try{
        for (Consumo consumo : listaConsumoTemp){
            ConsumoController.obterInstancia().inserir(consumo);
        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível estabelecer conexão com o banco de dados.");
        }
        
        this.listaConsumoTemp.clear();
        
    }//GEN-LAST:event_jbCadastrarConsumoActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarConsumo;
    private javax.swing.JButton jbBuscarComanda;
    private javax.swing.JButton jbCadastrarConsumo;
    private javax.swing.JButton jbLimparConsumo;
    private javax.swing.JPanel jdpPainelPrincipal;
    private javax.swing.JLabel jlDataEvento;
    private javax.swing.JLabel jlHorarioEvento;
    private javax.swing.JLabel jlNomeEvento;
    private javax.swing.JTable jtListaConsumoTemp;
    private javax.swing.JButton jtfBotaoComanda;
    private javax.swing.JButton jtfBotaoEvento;
    private javax.swing.JButton jtfBotaoProduto;
    private javax.swing.JButton jtfBotaoRelatorio;
    private javax.swing.JButton jtfBotaoSair;
    private javax.swing.JTextField jtfIdComanda;
    private javax.swing.JTextField jtfIdProduto;
    private javax.swing.JTextField jtfQuantidadeConsumo;
    // End of variables declaration//GEN-END:variables
}
