/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bartender.view;

import br.com.bartender.controller.ComandaController;
import br.com.bartender.controller.ConsumoController;
import br.com.bartender.model.Comanda;
import br.com.bartender.model.Consumo;
import br.com.bartender.model.Produto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;

/**
 *
 * @author eduardo
 */
public class TelaPrincipalUI extends javax.swing.JFrame {

        private ArrayList<Consumo> listaConsumoTemp = new ArrayList<Consumo>();
        private static TelaPrincipalUI instanciaTela;
    
    /*SINGLETON*/
    public static TelaPrincipalUI obterInstancia(){
        if ( instanciaTela == null ){
            instanciaTela = new TelaPrincipalUI();
        }
        return instanciaTela;
    }

    public JDesktopPane getPainelPrincipal(){
        return obterInstancia().getPainelPrincipal();    
    }
    
    /**
     * Creates new form TelaPrincipalUI
     */
    public TelaPrincipalUI() {
        initComponents();
    }
    
    public void atualizarTabelaConsumo(){
        DefaultTableModel tabelaConsumoTemp = new DefaultTableModel();
        tabelaConsumoTemp.setColumnIdentifiers(new String[] {"Produto","Valor unitario","Quantidade","Valor total"});
        
        for ( int i=0; i < this.listaConsumoTemp.size(); i++){
            tabelaConsumoTemp.addRow(new Object[] { this.listaConsumoTemp.get(i).getProdutoInserido().getNomeProduto(), 
                this.listaConsumoTemp.get(i).getProdutoInserido().getValorProduto(), this.listaConsumoTemp.get(i).getQuantidadeProduto(), 
            this.listaConsumoTemp.get(i).getValorTotal() });
        }
        jtListaConsumoTemp.setModel(tabelaConsumoTemp);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPainelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfBotaoEvento = new javax.swing.JButton();
        jtfBotaoComanda = new javax.swing.JButton();
        jtfBotaoProduto = new javax.swing.JButton();
        jtfBotaoRelatorio = new javax.swing.JButton();
        jtfBotaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jdpPainelTelas = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfIdComanda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaConsumoTemp = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jbAdicionarConsumo = new javax.swing.JButton();
        jtfIdProduto = new javax.swing.JTextField();
        jbCadastrarConsumo = new javax.swing.JButton();
        jbLimparConsumo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfQuantidadeConsumo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPainelPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jdpPainelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jdpPainelPrincipal.setForeground(new java.awt.Color(255, 0, 153));
        jdpPainelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 700));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/bartender/view/BarTenderLogo-Preto.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jtfBotaoEvento.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoEvento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoEvento.setText("Evento");
        jtfBotaoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoEventoActionPerformed(evt);
            }
        });

        jtfBotaoComanda.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoComanda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoComanda.setText("Comanda");
        jtfBotaoComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoComandaActionPerformed(evt);
            }
        });

        jtfBotaoProduto.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoProduto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoProduto.setText("Produto");
        jtfBotaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoProdutoActionPerformed(evt);
            }
        });

        jtfBotaoRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoRelatorio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoRelatorio.setText("Relatório");
        jtfBotaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoRelatorioActionPerformed(evt);
            }
        });

        jtfBotaoSair.setBackground(new java.awt.Color(255, 255, 255));
        jtfBotaoSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBotaoSair.setText("Sair");
        jtfBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBotaoSairActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 228, 228));
        jLabel1.setText("Bartender v1.0 - All Rights Reserved");
        jLabel1.setToolTipText("");
        jLabel1.setAlignmentX(0.5F);

        jdpPainelTelas.setBackground(new java.awt.Color(1, 1, 1));

        javax.swing.GroupLayout jdpPainelTelasLayout = new javax.swing.GroupLayout(jdpPainelTelas);
        jdpPainelTelas.setLayout(jdpPainelTelasLayout);
        jdpPainelTelasLayout.setHorizontalGroup(
            jdpPainelTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        jdpPainelTelasLayout.setVerticalGroup(
            jdpPainelTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Comanda:");

        jtfIdComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdComandaActionPerformed(evt);
            }
        });

        jtListaConsumoTemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Valor Unitário", "Quantidade", "Valor Total"
            }
        ));
        jtListaConsumoTemp.setGridColor(new java.awt.Color(0, 0, 0));
        jtListaConsumoTemp.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jtListaConsumoTemp.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jtListaConsumoTempComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaConsumoTemp);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Produto:");

        jbAdicionarConsumo.setText("Adicionar");
        jbAdicionarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarConsumoActionPerformed(evt);
            }
        });

        jbCadastrarConsumo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCadastrarConsumo.setText("Inserir");
        jbCadastrarConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarConsumoActionPerformed(evt);
            }
        });

        jbLimparConsumo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbLimparConsumo.setText("Limpar");
        jbLimparConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparConsumoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Consumo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(jtfIdComanda))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jtfQuantidadeConsumo)
                                .addGap(18, 18, 18)
                                .addComponent(jbAdicionarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jbCadastrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jbLimparConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(207, 207, 207))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIdComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfQuantidadeConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarConsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrarConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimparConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Menu");

        javax.swing.GroupLayout jdpPainelPrincipalLayout = new javax.swing.GroupLayout(jdpPainelPrincipal);
        jdpPainelPrincipal.setLayout(jdpPainelPrincipalLayout);
        jdpPainelPrincipalLayout.setHorizontalGroup(
            jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                                .addComponent(jtfBotaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfBotaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                                .addComponent(jtfBotaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfBotaoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jtfBotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel9)))
                .addGap(19, 19, 19)
                .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jdpPainelTelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        jdpPainelPrincipalLayout.setVerticalGroup(
            jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jdpPainelTelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jdpPainelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfBotaoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBotaoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jdpPainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfBotaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBotaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfBotaoSair)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdpPainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Se fosse na quarta fase, este trabalho não passava.");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jtfBotaoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoEventoActionPerformed
        // TODO add your handling code here:
        ManutencaoEventoUI manutencaoEvento = new ManutencaoEventoUI();
        jdpPainelTelas.removeAll();
        jdpPainelTelas.updateUI();
        jdpPainelTelas.add(manutencaoEvento);
        manutencaoEvento.setVisible(true);
    }//GEN-LAST:event_jtfBotaoEventoActionPerformed

    private void jtfBotaoComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoComandaActionPerformed
        // TODO add your handling code here:
        ManutencaoComandaUI manutencaoComanda = new ManutencaoComandaUI();
        jdpPainelTelas.removeAll();
        jdpPainelTelas.updateUI();
        jdpPainelTelas.add(manutencaoComanda);
        manutencaoComanda.setVisible(true);
    }//GEN-LAST:event_jtfBotaoComandaActionPerformed

    private void jtfBotaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoProdutoActionPerformed
        // TODO add your handling code here:
        ManutencaoProdutoUI manutencaoProduto = new ManutencaoProdutoUI();
        jdpPainelTelas.removeAll();
        jdpPainelTelas.updateUI();
        jdpPainelTelas.add(manutencaoProduto);
        manutencaoProduto.setVisible(true);
        
    }//GEN-LAST:event_jtfBotaoProdutoActionPerformed

    private void jtfBotaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoRelatorioActionPerformed
        // TODO add your handling code here:
        RelatorioUI relatorioUI = new RelatorioUI();
        jdpPainelTelas.removeAll();
        jdpPainelTelas.updateUI();
        jdpPainelTelas.add(relatorioUI);
        relatorioUI.setVisible(true);
    }//GEN-LAST:event_jtfBotaoRelatorioActionPerformed

    private void jtfBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBotaoSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jtfBotaoSairActionPerformed

    private void jtfIdComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdComandaActionPerformed

    private void jtListaConsumoTempComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jtListaConsumoTempComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtListaConsumoTempComponentAdded

    private void jbAdicionarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarConsumoActionPerformed
        // TODO add your handling code here:

        Consumo consumo = new Consumo();
        Comanda comandaRelacionada = new Comanda();
        Produto produtoInserido = new Produto();
        double valorTotal = 0;

        comandaRelacionada.setIdComanda(Integer.parseInt(jtfIdComanda.getText()));
        try{
        comandaRelacionada = ComandaController.obterInstancia().listarComandaId(comandaRelacionada);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível estabelecer conexão com o banco de dados.");
        }
        produtoInserido.setIdProduto(Integer.parseInt(jtfIdProduto.getText()));

        

        consumo.setComandaRelacionada(comandaRelacionada);
        consumo.setProdutoInserido(produtoInserido);
        consumo.setQuantidadeProduto(Integer.parseInt(jtfQuantidadeConsumo.getText()));

        this.listaConsumoTemp.add(consumo);
        atualizarTabelaConsumo();

        
    }//GEN-LAST:event_jbAdicionarConsumoActionPerformed

    private void jbCadastrarConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarConsumoActionPerformed
        // TODO add your handling code here:
        try{
            for (Consumo consumo : listaConsumoTemp){
                ConsumoController.obterInstancia().inserir(consumo);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possível estabelecer conexão com o banco de dados.");
        }

        this.listaConsumoTemp.clear();
        ((DefaultTableModel) jtListaConsumoTemp.getModel()).setNumRows(0);
        this.jtListaConsumoTemp.updateUI();

    }//GEN-LAST:event_jbCadastrarConsumoActionPerformed

    private void jbLimparConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparConsumoActionPerformed
        // TODO add your handling code here:
        
        
        this.listaConsumoTemp.clear();
        ((DefaultTableModel) jtListaConsumoTemp.getModel()).setNumRows(0);
        this.jtListaConsumoTemp.updateUI();
        
        
    }//GEN-LAST:event_jbLimparConsumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarConsumo;
    private javax.swing.JButton jbCadastrarConsumo;
    private javax.swing.JButton jbLimparConsumo;
    private javax.swing.JPanel jdpPainelPrincipal;
    private javax.swing.JPanel jdpPainelTelas;
    private javax.swing.JTable jtListaConsumoTemp;
    private javax.swing.JButton jtfBotaoComanda;
    private javax.swing.JButton jtfBotaoEvento;
    private javax.swing.JButton jtfBotaoProduto;
    private javax.swing.JButton jtfBotaoRelatorio;
    private javax.swing.JButton jtfBotaoSair;
    private javax.swing.JTextField jtfIdComanda;
    private javax.swing.JTextField jtfIdProduto;
    private javax.swing.JTextField jtfQuantidadeConsumo;
    // End of variables declaration//GEN-END:variables
}
